language: node_js

node_js:
  - 13

cache:
  yarn: true

before_install:
  - yarn global add semantic-release @semantic-release/git greenkeeper-lockfile

before_script:
  - greenkeeper-lockfile-update

after_script:
  - greenkeeper-lockfile-upload

script:
  - yarn lint
  - npx jest --coverage --coverageReporters=text-lcov | npx coveralls

deploy:
  provider: script
  script: npx semantic-release
  on:
    branch: master

addons:
  apt:
    update: true
