sudo: false

language: node_js

node_js:
  - "10"

cache:
  yarn: true

before_install:
  - yarn global add greenkeeper-lockfile@1

before_script:
  - greenkeeper-lockfile-update

after_script:
  - greenkeeper-lockfile-upload

script:
  - yarn lint
  - npx jest --coverage --coverageReporters=text-lcov | npx coveralls

deploy:
  provider: script
  skip_cleanup: true
  script:
    - yarn release
  on:
    branch: master

addons:
  apt:
    update: true
